name: deploy

on:
  push:
    branches:
      - feature/*
      - fix/*
      - prod

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Launch MongoDB
      uses: wbari/start-mongoDB@v0.2
      with:
        mongoDBVersion: 3.2

    - name: Start Redis
      uses: zhulik/redis-action@1.1.0
      with:
        redis version: '3.2'
        number of databases: 10

    - name: test
      env:
        ICPDAO_JWT_RSA_PUBLIC_KEY: ${{secrets.ICPDAO_JWT_RSA_PUBLIC_KEY}}
      run: |
        npm install
        pip install -r requirements.txt
        pytest tests

  deploy_prod:
    needs: [test]
    timeout-minutes: 20
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/feature/fushang318'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Configure AWS credentials from deploy account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: deploy
      env:
        SERVERLESS_ACCESS_KEY: ${{secrets.SERVERLESS_ACCESS_KEY}}
        ICPDAO_JWT_RSA_PUBLIC_KEY: ${{secrets.ICPDAO_JWT_RSA_PUBLIC_KEY}}
      run: |
        npm install -g serverless
        npm install
        sls deploy --stage prod
